SIG_PSPEP/Areas/Dtti/Controllers/DispLocalizacaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SIG_PSPEP.Areas.Dpq.Controllers;
using SIG_PSPEP.Context;
using SIG_PSPEP.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SIG_PSPEP.Areas.Dtti.Controllers
{
    [Area("Dtti")]
    [Authorize(Policy = "Require_Admin_ChDepar_ChSec_Esp")]
    public class DispLocalizacaoController : BaseController
    {
        private readonly ILogger<EfectividadesController> _logger;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public DispLocalizacaoController(
        AppDbContext context,
        UserManager<IdentityUser> userManager,
        SignInManager<IdentityUser> signInManager,
        ILogger<EfectividadesController> logger)
        : base(context)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _logger = logger;
        }

        // GET: Dtti/DispLocalizacao
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.DispositivoLocalizacoes.Include(d => d.Dispositivo).Include(d => d.OrgUnidPnaMinint).Include(d => d.User);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Dtti/DispLocalizacao/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dispositivoLocalizacao = await _context.DispositivoLocalizacoes
                .Include(d => d.Dispositivo)
                .Include(d => d.OrgUnidPnaMinint)
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dispositivoLocalizacao == null)
            {
                return NotFound();
            }

            return View(dispositivoLocalizacao);
        }

        // GET: Dtti/DispLocalizacao/Create
        public IActionResult Create(int id)
        {
            var dispositivo = _context.Dispositivos
                .Where(d => d.Id == id)
                .FirstOrDefault();

            if (dispositivo == null)
                return NotFound();

            ViewBag.EstadoTecnicoList = new SelectList(new List<string>
    {
        "Funcional",
        "Avariado",
        "Obsoleto",
        "Em Manutenção",
        "Em Reparação"
    });

            ViewData["OrgUnidPnaMinintId"] = new SelectList(
                _context.OrgUnidPnaMinints,
                "Id", "Sigla"
            );

            // devolve o modelo já com o dispositivo incluído
            return PartialView("_Create", new DispositivoLocalizacao
            {
                DispositivoId = dispositivo.Id,
                Dispositivo = dispositivo
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, DispositivoLocalizacao dispositivoLocalizacao)
        {
            var userId = userManager.GetUserId(User);

            var dispositivo = await _context.Dispositivos.FindAsync(dispositivoLocalizacao.DispositivoId);
            if (dispositivo == null)
                return Json(new { success = false, message = "Dispositivo não encontrado." });

            if (ModelState.IsValid)
            {
                dispositivoLocalizacao.UserId = userId;
                dispositivoLocalizacao.DispositivoId = id;
                _context.Add(dispositivoLocalizacao);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Localização cadastrada com sucesso!" });
            }

            // 🔹 Recarregar os SelectLists e o ViewData necessários
            ViewData["DispositivoId"] = new SelectList(
                _context.Dispositivos.Where(d => d.Id == dispositivoLocalizacao.DispositivoId),
                "Id", "Cod_Dispositivo",
                dispositivoLocalizacao.DispositivoId
            );

            ViewData["OrgUnidPnaMinintId"] = new SelectList(
                _context.OrgUnidPnaMinints, "Id", "Sigla", dispositivoLocalizacao.OrgUnidPnaMinintId
            );

            ViewBag.EstadoTecnicoList = new SelectList(new List<string>
    {
        "Funcional", "Avariado", "Obsoleto", "Em Manutenção", "Em Reparação"
    }, dispositivoLocalizacao.EstadoTecnico);

            return PartialView("_Create", dispositivoLocalizacao);
        }

        // GET: Dtti/DispLocalizacao/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dispositivoLocalizacao = await _context.DispositivoLocalizacoes.FindAsync(id);
            if (dispositivoLocalizacao == null)
            {
                return NotFound();
            }
            ViewData["DispositivoId"] = new SelectList(_context.Dispositivos, "Id", "Id", dispositivoLocalizacao.DispositivoId);
            ViewData["OrgUnidPnaMinintId"] = new SelectList(_context.OrgUnidPnaMinints, "Id", "Id", dispositivoLocalizacao.OrgUnidPnaMinintId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", dispositivoLocalizacao.UserId);
            return View(dispositivoLocalizacao);
        }

        // POST: Dtti/DispLocalizacao/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DispositivoId,OrgUnidPnaMinintId,Obs,EstadoTecnico,Id,Estado,DataRegisto,DataUltimaAlterecao,UserId")] DispositivoLocalizacao dispositivoLocalizacao)
        {
            if (id != dispositivoLocalizacao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dispositivoLocalizacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DispositivoLocalizacaoExists(dispositivoLocalizacao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DispositivoId"] = new SelectList(_context.Dispositivos, "Id", "Id", dispositivoLocalizacao.DispositivoId);
            ViewData["OrgUnidPnaMinintId"] = new SelectList(_context.OrgUnidPnaMinints, "Id", "Id", dispositivoLocalizacao.OrgUnidPnaMinintId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", dispositivoLocalizacao.UserId);
            return View(dispositivoLocalizacao);
        }

        // GET: Dtti/DispLocalizacao/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dispositivoLocalizacao = await _context.DispositivoLocalizacoes
                .Include(d => d.Dispositivo)
                .Include(d => d.OrgUnidPnaMinint)
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dispositivoLocalizacao == null)
            {
                return NotFound();
            }

            return View(dispositivoLocalizacao);
        }

        // POST: Dtti/DispLocalizacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dispositivoLocalizacao = await _context.DispositivoLocalizacoes.FindAsync(id);
            if (dispositivoLocalizacao != null)
            {
                _context.DispositivoLocalizacoes.Remove(dispositivoLocalizacao);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DispositivoLocalizacaoExists(int id)
        {
            return _context.DispositivoLocalizacoes.Any(e => e.Id == id);
        }
    }
}

SIG_PSPEP/Areas/Dtti/Views/DispLocalizacao/Delete.cshtml
@model SIG_PSPEP.Entidades.DispositivoLocalizacao

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DispositivoLocalizacao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Obs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Obs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoTecnico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoTecnico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dispositivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dispositivo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrgUnidPnaMinint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrgUnidPnaMinint.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRegisto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRegisto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataUltimaAlterecao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataUltimaAlterecao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SIG_PSPEP/Areas/Dtti/Views/DispLocalizacao/Details.cshtml
@model SIG_PSPEP.Entidades.DispositivoLocalizacao

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DispositivoLocalizacao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Obs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Obs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoTecnico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoTecnico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dispositivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dispositivo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrgUnidPnaMinint)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrgUnidPnaMinint.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRegisto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRegisto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataUltimaAlterecao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataUltimaAlterecao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SIG_PSPEP/Areas/Dtti/Views/DispLocalizacao/Edit.cshtml
@model SIG_PSPEP.Entidades.DispositivoLocalizacao

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DispositivoLocalizacao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DispositivoId" class="control-label"></label>
                <select asp-for="DispositivoId" class="form-control" asp-items="ViewBag.DispositivoId"></select>
                <span asp-validation-for="DispositivoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgUnidPnaMinintId" class="control-label"></label>
                <select asp-for="OrgUnidPnaMinintId" class="form-control" asp-items="ViewBag.OrgUnidPnaMinintId"></select>
                <span asp-validation-for="OrgUnidPnaMinintId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Obs" class="control-label"></label>
                <input asp-for="Obs" class="form-control" />
                <span asp-validation-for="Obs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoTecnico" class="control-label"></label>
                <input asp-for="EstadoTecnico" class="form-control" />
                <span asp-validation-for="EstadoTecnico" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DataRegisto" class="control-label"></label>
                <input asp-for="DataRegisto" class="form-control" />
                <span asp-validation-for="DataRegisto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataUltimaAlterecao" class="control-label"></label>
                <input asp-for="DataUltimaAlterecao" class="form-control" />
                <span asp-validation-for="DataUltimaAlterecao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIG_PSPEP/Areas/Dtti/Views/DispLocalizacao/Index.cshtml
@model IEnumerable<SIG_PSPEP.Entidades.DispositivoLocalizacao>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Obs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoTecnico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dispositivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrgUnidPnaMinint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataRegisto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataUltimaAlterecao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Obs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoTecnico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrgUnidPnaMinint.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataRegisto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataUltimaAlterecao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SIG_PSPEP/Areas/Dtti/Views/DispLocalizacao/_Create.cshtml
@model SIG_PSPEP.Entidades.DispositivoLocalizacao

<form method="post" asp-action="Create" asp-controller="DispLocalizacao" asp-area="Dtti" onsubmit="return submitForm(this)">
    <div class="modal-header">
        <h5 class="modal-title">Adicionar Localização do Dispositivo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>

    <div class="modal-body">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <!-- Apenas exibir o dispositivo -->
                <input type="hidden" asp-for="DispositivoId" />
                <input type="text" class="form-control" value="@Model?.Dispositivo?.Cod_Dispositivo ?? " —"" readonly />

                <!-- Unidade Orgânica -->
                <div class="form-group">
                    <label class="control-label small-label">Unidade Orgânica</label>
                    <select asp-for="OrgUnidPnaMinintId" class="form-control"
                            asp-items="@(ViewData["OrgUnidPnaMinintId"] as SelectList)" required>
                        <option value="">-- Selecione a Unidade --</option>
                    </select>
                    <span asp-validation-for="OrgUnidPnaMinintId" class="text-danger"></span>
                </div>

                <!-- Estado Técnico -->
                <div class="form-group">
                    <label class="control-label small-label">Estado Técnico</label>
                    <select asp-for="EstadoTecnico" class="form-control" asp-items="ViewBag.EstadoTecnicoList" required>
                        <option value="">-- Selecione o Estado --</option>
                    </select>
                    <span asp-validation-for="EstadoTecnico" class="text-danger"></span>
                </div>

                <!-- Observações -->
                <div class="form-group">
                    <label class="control-label small-label">Descrição da Localização</label>
                    <input asp-for="Obs" class="form-control" placeholder="Observação" />
                    <span asp-validation-for="Obs" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="custom2-btn btn-2-success">Salvar</button>
        <button type="button" class="custom2-btn btn-2-dark-blue" data-bs-dismiss="modal">Cancelar</button>
    </div>
</form>

@section Scripts {
    <script>
        function submitForm(form) {
            $.post(form.action, $(form).serialize(), function (result) {
                if (result.success) {
                    toastr.success(result.message || "Localização adicionada com sucesso!");
                    setTimeout(() => location.reload(), 1200);
                } else if (result.message) {
                    toastr.warning(result.message);
                } else {
                    $('#modalContent').html(result);
                }
            }).fail(function () {
                toastr.error("Ocorreu um erro ao processar a solicitação.");
            });
            return false;
        }
    </script>
}